import Classes.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed's PC
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_EmpName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_EmpCNIC = new javax.swing.JTextField();
        txt_EmpAddress = new javax.swing.JTextField();
        rBtn_EmpMale = new javax.swing.JRadioButton();
        rBtn_EmpFemale = new javax.swing.JRadioButton();
        btn_AddEmployee = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jdc_EmpDOH = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jdc_EmpDOB = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txt_EmpPhoneNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Employee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));
        getContentPane().add(txt_EmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));
        getContentPane().add(txt_EmpCNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 230, 30));
        getContentPane().add(txt_EmpAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 230, 30));

        rBtn_EmpMale.setText("Male");
        getContentPane().add(rBtn_EmpMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        rBtn_EmpFemale.setText("Female");
        getContentPane().add(rBtn_EmpFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, -1, -1));

        btn_AddEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_AddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        btn_AddEmployee.setText("Submit");
        btn_AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Hired Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));
        getContentPane().add(jdc_EmpDOH, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 230, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date of Birth");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));
        getContentPane().add(jdc_EmpDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 225, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CNIC Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));
        getContentPane().add(txt_EmpPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 230, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed
    String empGender;
    private void btn_AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddEmployeeActionPerformed
        try{
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        String empDOB =dateFormat.format(jdc_EmpDOB.getDate());
        String empDOH =dateFormat.format(jdc_EmpDOH.getDate());        //DOH=Date of Hired
        String empName=txt_EmpName.getText();
        String empPhoneNumber=txt_EmpPhoneNumber.getText();
        String empAddress=txt_EmpAddress.getText();
        String empCNIC=txt_EmpCNIC.getText();
        if(rBtn_EmpMale.isSelected()){
            empGender="Male";
        }
        if(rBtn_EmpFemale.isSelected()){
            empGender="Female";
        }
        if(empName.equals(""))
        JOptionPane.showMessageDialog(null, "Name can't be left empty");
        else if(empPhoneNumber.equals("")||empPhoneNumber.length()!=11)
        JOptionPane.showMessageDialog(null, "Please enter valid mobile number without dash");
        else if(empAddress.equals(""))
        JOptionPane.showMessageDialog(null, "Please enter address field");
        else if(empCNIC.equals("")||empCNIC.length()!=15)
        JOptionPane.showMessageDialog(null, "Please enter correct cnic with dashes");
        else if(!(rBtn_EmpMale.isSelected()||rBtn_EmpFemale.isSelected()))
        JOptionPane.showMessageDialog(null, "Gender is not specified");
        else if(empDOB.equals("")){
            JOptionPane.showMessageDialog(null, "Please specify date of birth");
        }
        else if(empDOB.equals("")){
            JOptionPane.showMessageDialog(null, "Please specify hired date");
        }
        else{
                Connection con=ConnectionProvider.getcon();
                PreparedStatement ps=con.prepareStatement("insert into EmployeeDetails (employeeName,employeeDOB,employeePhoneNumber,employeeCNIC,employeeGender,employeeHiredDate,employeeAddress) values (?,?,?,?,?,?,?)");
                ps.setString(1,empName);
                ps.setString(2,empDOB);
                ps.setString(3,empPhoneNumber);
                ps.setString(4,empCNIC);
                ps.setString(5,empGender);
                ps.setString(6,empDOH);
                ps.setString(7,empAddress);
                ps.executeUpdate();
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select employeeID from  EmployeeDetails where employeePhoneNumber='"+empPhoneNumber+"'");
                if(rs.next()){
                    int empID = rs.getInt("employeeID");
                    JOptionPane.showMessageDialog(null,"Employee added successfully.Employee id is: "+empID);
                    setVisible(false);
                    new Dashboard().setVisible(true);
                con.close();
            }
        }   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please fill entire form");
        }
    }//GEN-LAST:event_btn_AddEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddEmployee;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser jdc_EmpDOB;
    private com.toedter.calendar.JDateChooser jdc_EmpDOH;
    private javax.swing.JRadioButton rBtn_EmpFemale;
    private javax.swing.JRadioButton rBtn_EmpMale;
    private javax.swing.JTextField txt_EmpAddress;
    private javax.swing.JTextField txt_EmpCNIC;
    private javax.swing.JTextField txt_EmpName;
    private javax.swing.JTextField txt_EmpPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
