import Classes.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed's PC
 */
public class AddMeasurements extends javax.swing.JFrame {

    /**
     * Creates new form AddMeasurements
     */
    public AddMeasurements() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        txt_k_length.setVisible(false);
        txt_k_width.setVisible(false);
        txt_sh_length.setVisible(false);
        txt_sh_waist.setVisible(false);
        txt_sleevesLength.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        submit.setVisible(false);
        txt_c_name.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        length = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        txt_k_width = new javax.swing.JSpinner();
        txt_sh_length = new javax.swing.JSpinner();
        txt_sleevesLength = new javax.swing.JSpinner();
        txt_sh_waist = new javax.swing.JSpinner();
        txt_k_length = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewCustomer = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_c_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_c_name = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        btn_viewCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(length, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 49, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Measurements");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 44, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("       Shalwar Measurements(inches)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 250, 52));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("      Kameez Measurements(inches)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 240, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(" Length");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 306, 58, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" Length");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 56, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("  Waist");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 56, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("  Width");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 365, 58, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sleeves Length");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 412, -1, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 11, 30, 30));

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        txt_k_width.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_k_width, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 364, 105, 30));

        txt_sh_length.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_sh_length, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 105, 30));

        txt_sleevesLength.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_sleevesLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 413, 105, 30));

        txt_sh_waist.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_sh_waist, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 105, 30));

        txt_k_length.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_k_length, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 306, 105, 30));

        viewCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Contact", "Address", "Gender", "Age"
            }
        ));
        jScrollPane1.setViewportView(viewCustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 78, 563, 419));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Please enter Customer ID whom you want to add measurements");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        getContentPane().add(txt_c_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 120, 28));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Customer Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));
        getContentPane().add(txt_c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 200, 28));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        btn_viewCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_viewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_view_40px.png"))); // NOI18N
        btn_viewCustomer.setText("View Customer");
        btn_viewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 190, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if((float)txt_k_length.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Kameez Length");
        }
        else if((float)txt_k_width.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Kameez Width");
        }
        else if((float)txt_sleevesLength.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Sleeves Length");
        }        
        else if((float)txt_sh_length.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Shalwar Length");
        }
        else if((float)txt_sh_waist.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Shalwar Waist");
        }
        else{
            try{
                Connection con=ConnectionProvider.getcon();
                PreparedStatement ps=con.prepareStatement("insert into MeasurementDetails (customerID,shalwarLength,shalwarWaist,kameezLength,kameezWidth,sleevesLength) values (?,?,?,?,?,?)");
                ps.setInt(1,custID);
                ps.setFloat(2,(float)txt_sh_length.getValue());
                ps.setFloat(3,(float)txt_sh_waist.getValue());
                ps.setFloat(4,(float)txt_k_length.getValue());
                ps.setFloat(5,(float)txt_k_width.getValue());
                ps.setFloat(6,(float)txt_sleevesLength.getValue());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Measurements added successfully");
                con.close();
                setVisible(false);
                new Dashboard().setVisible(true);
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }        
    }//GEN-LAST:event_submitActionPerformed
    int custID;
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{
            Connection con=ConnectionProvider.getcon();
            Statement st1=con.createStatement();
            custID=Integer.parseInt(txt_c_ID.getText());
            ResultSet rs1=st1.executeQuery("select customerName from  CustomerDetails where customerID='"+custID+"'");
            if(rs1.next()){
                Statement st2=con.createStatement();
                ResultSet rs2=st2.executeQuery("select customerID from  MeasurementDetails where customerID='"+custID+"'");
                if(rs2.next()){
                    txt_c_name.setText(rs1.getString("customerName"));
                    txt_k_length.setVisible(false);
                    txt_k_width.setVisible(false);
                    txt_sh_length.setVisible(false);
                    txt_sh_waist.setVisible(false);
                    txt_sleevesLength.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    submit.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Measurements already added for this customer");
                    con.close();
                    txt_c_ID.setText("");
                    txt_c_name.setText("");
                    
                }
                else{
                    txt_c_name.setText(rs1.getString("customerName"));
                    txt_k_length.setVisible(true);
                    txt_k_width.setVisible(true);
                    txt_sh_length.setVisible(true);
                    txt_sh_waist.setVisible(true);
                    txt_sleevesLength.setVisible(true);
                    jLabel2.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    submit.setVisible(true);
                    con.close();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No such Customer found");
                txt_c_ID.setText("");
            }
        }
        catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter an integer in Customer ID field");
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void btn_viewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewCustomerActionPerformed
        DefaultTableModel model=(DefaultTableModel)viewCustomer.getModel();
        try{
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from  CustomerDetails");
            while(rs.next()){
                model.addRow(new Object[]{rs.getInt("customerID"),rs.getString("customerName"),rs.getString("customerPhoneNumber"),rs.getString("customerAddress"),rs.getString("customerGender"),rs.getInt("customerAge")});
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_viewCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMeasurements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_viewCustomer;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel length;
    private javax.swing.JButton search;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txt_c_ID;
    private javax.swing.JTextField txt_c_name;
    private javax.swing.JSpinner txt_k_length;
    private javax.swing.JSpinner txt_k_width;
    private javax.swing.JSpinner txt_sh_length;
    private javax.swing.JSpinner txt_sh_waist;
    private javax.swing.JSpinner txt_sleevesLength;
    private javax.swing.JTable viewCustomer;
    // End of variables declaration//GEN-END:variables
}
