import Classes.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JFrame;


public class BookOrder extends javax.swing.JFrame {

    /**
     * Creates new form BookOrder
     */
    public BookOrder() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        txt_c_Name.setEditable(false);
        txt_m_ID.setEditable(false);
        txt_gender.setEnabled(false);
        txt_gender.setSelectedIndex(0);
        txt_rAmount.setEditable(false);
        txt_dDate.setVisible(false);
        txt_bDate.setVisible(false);
        txt_suits.setVisible(false);
        txt_tAmount.setVisible(false);
        txt_pAmount.setVisible(false);
        txt_rAmount.setVisible(false);
        txt_MaleSuit.setVisible(false);
        txt_FemaleSuit.setVisible(false);
        txt_extraNote.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel14.setVisible(false);
        book.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_c_ID = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_c_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_m_ID = new javax.swing.JTextField();
        txt_bDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_tAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_pAmount = new javax.swing.JTextField();
        txt_rAmount = new javax.swing.JTextField();
        book = new javax.swing.JButton();
        txt_FemaleSuit = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_MaleSuit = new javax.swing.JComboBox<>();
        txt_gender = new javax.swing.JComboBox<>();
        txt_suits = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        txt_extraNote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 11, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Book Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 25, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Please enter Customer ID whom you want to book order");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));
        getContentPane().add(txt_c_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 120, 28));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));
        getContentPane().add(txt_c_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 186, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Measurement ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));
        getContentPane().add(txt_m_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 133, 32));
        getContentPane().add(txt_bDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 180, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Extra Note");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Delivery Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("No.of Suits");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));
        getContentPane().add(txt_dDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 180, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));
        getContentPane().add(txt_tAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, 180, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Paid Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Remaining Amount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, -1, -1));
        getContentPane().add(txt_pAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, 180, 31));
        getContentPane().add(txt_rAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 180, 29));

        book.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_40px.png"))); // NOI18N
        book.setText("Book Order");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 201, -1));

        txt_FemaleSuit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Straight Shalwar Kameez", "Trouser Shirt", "Maxi", "Saarhi", "Frok" }));
        txt_FemaleSuit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_FemaleSuitItemStateChanged(evt);
            }
        });
        getContentPane().add(txt_FemaleSuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 180, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Suit type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gender");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, -1, -1));

        txt_MaleSuit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Shalwar Kameez", "Trouser Kameez", "Pent Coat", "Waist Coat" }));
        txt_MaleSuit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_MaleSuitItemStateChanged(evt);
            }
        });
        getContentPane().add(txt_MaleSuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 180, 30));

        txt_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        getContentPane().add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 110, 30));

        txt_suits.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(txt_suits, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Booked Date");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));
        getContentPane().add(txt_extraNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 530, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed
    int custID;
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        txt_c_Name.setEditable(false);
        txt_m_ID.setEditable(false);
        txt_gender.setEnabled(false);
        txt_gender.setSelectedIndex(0);
        txt_dDate.setVisible(false);
        txt_bDate.setVisible(false);
        txt_suits.setVisible(false);
        txt_tAmount.setVisible(false);
        txt_pAmount.setVisible(false);
        txt_rAmount.setVisible(false);
        txt_MaleSuit.setVisible(false);
        txt_FemaleSuit.setVisible(false);
        txt_extraNote.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel14.setVisible(false);
        book.setVisible(false);
        try{
            Connection con=ConnectionProvider.getcon();
            Statement st1=con.createStatement();
            custID=Integer.parseInt(txt_c_ID.getText());
            ResultSet rs1=st1.executeQuery("select * from  CustomerDetails where customerID='"+custID+"'");
            if(rs1.next()){
                Statement st2=con.createStatement();
                ResultSet rs2=st2.executeQuery("select measurementID from  MeasurementDetails where customerID='"+custID+"'");
                if(rs2.next()){
                    txt_c_Name.setText(rs1.getString("customerName"));
                    txt_m_ID.setText(rs2.getString("measurementID"));
                    if(rs1.getString("customerGender").equalsIgnoreCase("male")){
                        txt_gender.setSelectedIndex(1);
                        txt_FemaleSuit.setVisible(false);
                        jLabel11.setVisible(true);
                        txt_MaleSuit.setVisible(true);
                    }
                    else{
                        txt_gender.setSelectedIndex(2);
                        txt_MaleSuit.setVisible(false);
                        jLabel11.setVisible(true);
                        txt_FemaleSuit.setVisible(true);
                    }
                }
                else{
                    txt_c_Name.setText(rs1.getString("customerName"));
                    if(rs1.getString("customerGender").equalsIgnoreCase("male")){
                        txt_gender.setSelectedIndex(1);
                    }
                    else{
                        txt_gender.setSelectedIndex(2);
                    }
                    JOptionPane.showMessageDialog(null, "No measurements added for this customer. First add measurements details");
                    con.close();
                }
            }
            else{
                txt_c_Name.setText("");
                txt_m_ID.setText("");
                JOptionPane.showMessageDialog(null, "No such Customer found");
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter an integer in Customer ID field");
            txt_c_ID.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        try{
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String bookedDate =sdf.format(txt_bDate.getDate());
        String deliveryDate =sdf.format(txt_dDate.getDate());
        if(bookedDate.equals("")){
            JOptionPane.showMessageDialog(null, "Please specify booked date");
        }
        else if(deliveryDate.equals("")){
            JOptionPane.showMessageDialog(null, "Please specify delivery date");
        }
        else if((Integer)txt_suits.getValue()==0){
            JOptionPane.showMessageDialog(null, "Suits should be minimum one");
        }
        else if(txt_tAmount.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Total amount field can't be left empty");
        }
        else if(txt_pAmount.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Paid amount field can't be left empty");
        }
        else if(Integer.parseInt(txt_tAmount.getText())==0){
            JOptionPane.showMessageDialog(null, "Total amount should not be zero");
        }
        else if(Integer.parseInt(txt_pAmount.getText())>Integer.parseInt(txt_tAmount.getText())){
            JOptionPane.showMessageDialog(null, "Paid amount should not be more than total amount");
        }
        else if(txt_gender.getSelectedIndex()==1){
            int remAmount=Integer.parseInt(txt_tAmount.getText())-Integer.parseInt(txt_pAmount.getText());
            txt_rAmount.setText(String.valueOf(remAmount));
            Connection con=ConnectionProvider.getcon();
            PreparedStatement ps=con.prepareStatement("insert into OrderDetails (customerID,bookedDate,returnDate,no_of_suits,totalAmount,paidAmount,remainingAmount,extraNote,suitType) values (?,?,?,?,?,?,?,?,?)");
            ps.setInt(1,custID);
            ps.setString(2, bookedDate);
            ps.setString(3, deliveryDate);
            ps.setFloat(4,(Integer)txt_suits.getValue());
            ps.setFloat(5,Integer.parseInt(txt_tAmount.getText()));
            ps.setFloat(6,Integer.parseInt(txt_pAmount.getText()));
            ps.setFloat(7,remAmount);
            ps.setString(8,txt_extraNote.getText());
            ps.setString(9,String.valueOf(txt_MaleSuit.getSelectedItem()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Order saved successfully. Your remaining amount is "+remAmount);
            setVisible(false);
            new Dashboard().setVisible(true);
            con.close();
        }
        else{
            int remAmount=Integer.parseInt(txt_tAmount.getText())-Integer.parseInt(txt_pAmount.getText());
            txt_rAmount.setText(String.valueOf(remAmount));
            Connection con=ConnectionProvider.getcon();
            PreparedStatement ps=con.prepareStatement("insert into OrderDetails (customerID,bookedDate,returnDate,no_of_suits,totalAmount,paidAmount,remainingAmount,extraNote,suitType) values (?,?,?,?,?,?,?,?,?)");
            ps.setInt(1,custID);
            ps.setString(2, bookedDate);
            ps.setString(3, deliveryDate);
            ps.setFloat(4,(Integer)txt_suits.getValue());
            ps.setFloat(5,Integer.parseInt(txt_tAmount.getText()));
            ps.setFloat(6,Integer.parseInt(txt_pAmount.getText()));
            ps.setFloat(7,remAmount);
            ps.setString(8,txt_extraNote.getText());
            ps.setString(9,String.valueOf(txt_FemaleSuit.getSelectedItem()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Order saved successfully. Your remaining amount is "+remAmount);
            setVisible(false);
            new Dashboard().setVisible(true);
            con.close();
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Total,Paid,Remaining amount fields should  be of integer type");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please fill entire form");
        }
    }//GEN-LAST:event_bookActionPerformed

    private void txt_MaleSuitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_MaleSuitItemStateChanged
        txt_dDate.setVisible(true);
        txt_bDate.setVisible(true);
        txt_suits.setVisible(true);
        txt_tAmount.setVisible(true);
        txt_pAmount.setVisible(true);
        txt_rAmount.setVisible(true);
        txt_extraNote.setVisible(true);
        jLabel10.setVisible(true);
        jLabel4.setVisible(true);
        jLabel14.setVisible(true); 
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        book.setVisible(true);
        if(txt_MaleSuit.getSelectedIndex()==0){
            txt_dDate.setVisible(false);
            txt_bDate.setVisible(false);
            txt_suits.setVisible(false);
            txt_tAmount.setVisible(false);
            txt_pAmount.setVisible(false);
            txt_rAmount.setVisible(false);
            txt_extraNote.setVisible(false);
            jLabel10.setVisible(false);
            jLabel4.setVisible(false);
            jLabel14.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            book.setVisible(false);
        }               
    }//GEN-LAST:event_txt_MaleSuitItemStateChanged

    private void txt_FemaleSuitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_FemaleSuitItemStateChanged
        txt_dDate.setVisible(true);
        txt_bDate.setVisible(true);
        txt_suits.setVisible(true);
        txt_tAmount.setVisible(true);
        txt_pAmount.setVisible(true);
        txt_rAmount.setVisible(true);
        txt_extraNote.setVisible(true);
        jLabel10.setVisible(true);
        jLabel4.setVisible(true);
        jLabel14.setVisible(true); 
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        book.setVisible(true);
        if(txt_FemaleSuit.getSelectedIndex()==0){
            txt_dDate.setVisible(false);
            txt_bDate.setVisible(false);
            txt_suits.setVisible(false);
            txt_tAmount.setVisible(false);
            txt_pAmount.setVisible(false);
            txt_rAmount.setVisible(false);
            txt_extraNote.setVisible(false);
            jLabel10.setVisible(false);
            jLabel4.setVisible(false);
            jLabel14.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            book.setVisible(false);
        }
    }//GEN-LAST:event_txt_FemaleSuitItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> txt_FemaleSuit;
    private javax.swing.JComboBox<String> txt_MaleSuit;
    private com.toedter.calendar.JDateChooser txt_bDate;
    private javax.swing.JTextField txt_c_ID;
    private javax.swing.JTextField txt_c_Name;
    private com.toedter.calendar.JDateChooser txt_dDate;
    private javax.swing.JTextField txt_extraNote;
    private javax.swing.JComboBox<String> txt_gender;
    private javax.swing.JTextField txt_m_ID;
    private javax.swing.JTextField txt_pAmount;
    private javax.swing.JTextField txt_rAmount;
    private javax.swing.JSpinner txt_suits;
    private javax.swing.JTextField txt_tAmount;
    // End of variables declaration//GEN-END:variables
}
