
import Classes.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed's PC
 */
public class UpdateMeasurements extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMeasurements
     */
    public UpdateMeasurements() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        txt_k_length.setVisible(false);
        txt_k_width.setVisible(false);
        txt_sh_length.setVisible(false);
        txt_sh_waist.setVisible(false);
        txt_sleevesLength.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        update.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewMeasurements = new javax.swing.JTable();
        btn_viewMeasurement = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_k_length = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txt_k_width = new javax.swing.JSpinner();
        txt_sleevesLength = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sh_length = new javax.swing.JSpinner();
        txt_sh_waist = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Measurements");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 30, 30));

        viewMeasurements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer ID", "Measurement ID", "Shalwar Length", "Shalwar Waist", "Kameez Length", "Kameez Width", "Sleeves Length"
            }
        ));
        viewMeasurements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMeasurementsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewMeasurements);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 149, 859, -1));

        btn_viewMeasurement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_viewMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_view_40px.png"))); // NOI18N
        btn_viewMeasurement.setText("Preview Measurements");
        btn_viewMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewMeasurementActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewMeasurement, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 254, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("      Kameez Measurements(inches)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 240, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(" Length");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 58, 30));

        txt_k_length.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_k_length, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 105, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("  Width");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 58, 27));

        txt_k_width.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_k_width, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 105, 30));

        txt_sleevesLength.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_sleevesLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 105, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sleeves Length");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("       Shalwar Measurements(inches)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 52));

        txt_sh_length.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_sh_length, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 105, 30));

        txt_sh_waist.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));
        getContentPane().add(txt_sh_waist, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 105, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("  Waist");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 56, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" Length");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 56, 28));

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Select the row you want to update");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void btn_viewMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewMeasurementActionPerformed
        DefaultTableModel model=(DefaultTableModel)viewMeasurements.getModel();
        try{
            Connection con=ConnectionProvider.getcon();
            Statement st1=con.createStatement();
            ResultSet rs1=st1.executeQuery("select * from  MeasurementDetails");
            while(rs1.next()){
                int ID=rs1.getInt("customerID");
                Statement st2=con.createStatement();
                ResultSet rs2=st2.executeQuery("select * from CustomerDetails where customerID='"+ID+"'");
                if(rs2.next()){
                    model.addRow(new Object[]{rs2.getString("customerName"),rs1.getInt("customerID"),rs1.getInt("measurementID"),rs1.getFloat("shalwarLength"),rs1.getFloat("shalwarWaist"),rs1.getFloat("kameezLength"),rs1.getFloat("kameezWidth"),rs1.getFloat("sleevesLength")});
                }
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_viewMeasurementActionPerformed
    int m_ID;
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if((float)txt_k_length.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Kameez Length");
        }
        else if((float)txt_k_width.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Kameez Width");
        }
        else if((float)txt_sleevesLength.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Sleeves Length");
        }
        else if((float)txt_sh_length.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Shalwar Length");
        }
        else if((float)txt_sh_waist.getValue()==0){
            JOptionPane.showMessageDialog(null, " Please specify correct Shalwar Waist");
        }
        else{
            int a;
            a = JOptionPane.showConfirmDialog(null,"Are you sure to update measurements","Select",JOptionPane.YES_NO_OPTION);
            if(a==0)
            {
            try{
                Connection con=ConnectionProvider.getcon();
                PreparedStatement ps=con.prepareStatement("update MeasurementDetails set shalwarLength=?,shalwarWaist=?,kameezLength=?,kameezWidth=?,sleevesLength=? where measurementID='"+m_ID+"'");
                ps.setFloat(1,(float)txt_sh_length.getValue());
                ps.setFloat(2,(float)txt_sh_waist.getValue());
                ps.setFloat(3,(float)txt_k_length.getValue());
                ps.setFloat(4,(float)txt_k_width.getValue());
                ps.setFloat(5,(float)txt_sleevesLength.getValue());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Measurements updated successfully");
                con.close();
                setVisible(false);
                new UpdateMeasurements().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void viewMeasurementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMeasurementsMouseClicked
        txt_k_length.setVisible(true);
        txt_k_width.setVisible(true);
        txt_sh_length.setVisible(true);
        txt_sh_waist.setVisible(true);
        txt_sleevesLength.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        update.setVisible(true);
        int index=viewMeasurements.getSelectedRow();
        TableModel model=viewMeasurements.getModel();
        txt_k_length.setValue(model.getValueAt(index, 5));
        txt_k_width.setValue(model.getValueAt(index, 6));
        txt_sleevesLength.setValue(model.getValueAt(index, 7));
        txt_sh_length.setValue(model.getValueAt(index, 3));
        txt_sh_waist.setValue(model.getValueAt(index, 4));
        m_ID=(Integer)model.getValueAt(index, 2);
        
    }//GEN-LAST:event_viewMeasurementsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMeasurements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMeasurements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_viewMeasurement;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner txt_k_length;
    private javax.swing.JSpinner txt_k_width;
    private javax.swing.JSpinner txt_sh_length;
    private javax.swing.JSpinner txt_sh_waist;
    private javax.swing.JSpinner txt_sleevesLength;
    private javax.swing.JButton update;
    private javax.swing.JTable viewMeasurements;
    // End of variables declaration//GEN-END:variables
}
